apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData: # Using stringData for raw text setup
  mysql-root-password: "SuperSecretPassword123!"
  mysql-database: "capstone_db"