apiVersion: v1
kind: Service
metadata:
  name: mysql-internal-svc
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None # Headless service for internal routing
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-internal-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-database
          ports:
            - containerPort: 3306
