apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: split-router-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: flask-backend-svc
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: flask-backend-svc
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-frontend-svc
                port:
                  number: 80
